services:
  trino:
      image: trinodb/trino:latest
      container_name: trino-kidopi
      hostname: trino-kidopi
      ports:
        - "${TRINO_PORT:-8080}:8080"
      volumes:
        - ./trino/trino-config:/etc/trino
        - ./trino/init-trino.sh:/docker-entrypoint-init.d/init-trino.sh
      env_file:
        - .env
      entrypoint: ["/bin/bash", "/docker-entrypoint-init.d/init-trino.sh"]
      networks:
        - kidopi_sistemas_dev-network
  metabase:
    networks:
      - kidopi_sistemas_dev-network

networks:
  kidopi_sistemas_dev-network:
    external: true